name: 'discord-issue-message'
description: 'Create Discord message on issue creation'
author: 'dan-mba'
inputs:
  discord_token:
    required: true
    description: 'Discord server token'
  discord_channel:
    required: true
    description: 'Discord channel id'
  message:
    required: false
    description: 'message text (only use if not an issue)'

runs:
  using: 'node16'
  main: 'dist/index.js'
